### ISSUE TITLE
Add support for PyYAML in install_requires

### ISSUE THREAD

**Issue by DmytroLitvinov** [sonatype-nexus-community/ossindex-python#8]
Hi there,

I am trying to upgrade my packages with `pip-tools` and I see that package is used for `jake` which recently released v2.
I see that there is [support of PyYAML](https://github.com/sonatype-nexus-community/ossindex-python/blob/a4092c4fac7716c784644d4db142be4e69fc061d/pyproject.toml#L45) `^5.4.1` - so v6 is not supported but it was released in 20th October, 2021 [(link)](https://pypi.org/project/PyYAML/#history)

Here is a traceback of issue:
```
Could not find a version that matches pyyaml<6.0.0,==6.0,>=5.1,>=5.2,>=5.3.1,>=5.4.1 (from -r requirements.txt (line 612))
Tried: 3.10, 3.10, 3.11, 3.11, 3.12, 3.12, 3.13, 5.1, 5.1.1, 5.1.2, 5.2, 5.3, 5.3.1, 5.4, 5.4, 5.4.1, 5.4.1, 6.0, 6.0
Skipped pre-versions: 3.13b1, 3.13rc1, 4.2b1, 4.2b2, 4.2b4, 5.1b1, 5.1b3, 5.1b5, 5.2b1, 5.3b1, 5.4b1, 5.4b1, 5.4b2, 5.4b2, 6.0b1, 6.0b1
There are incompatible versions in the resolved dependencies:
  pyyaml==6.0 (from -r requirements.txt (line 612))
  PyYAML>=5.1 (from uvicorn[standard]==0.17.6->-r requirements.txt (line 720))
  PyYAML<6.0.0,>=5.4.1 (from ossindex-lib==1.0.0->jake==2.0.0->-r requirements-dev.in (line 23))
  PyYAML>=5.3.1 (from bandit==1.7.4->-r requirements-dev.in (line 24))
  pyyaml>=5.1 (from pre-commit==2.17.0->-r requirements-dev.in (line 16))
  pyyaml (from dparse==0.5.1->safety==1.10.3->-r requirements-dev.in (line 20))
  pyyaml>=5.2 (from libcst==0.3.23->autotyping==21.12.0->-r requirements-dev.in (line 26))
```

Is there any possibility to release new version of package with support for PyYAML v6? (I believe it is only adding support in `pyproject.toml` file.)

**Comment by madpah** [comment]
Hi @DmytroLitvinov - thanks for catching this - an honest mistake. We'll get a new release rolled with this dependency restriction loosened shortly!

**Comment by DmytroLitvinov** [comment]
Hi @madpah ,
Do you need my help in releasing it?

**Comment by tomlinsj** [comment]
is there a timeline on when this will be resolved?

**Comment by madpah** [comment]
Apologies for the delay @DmytroLitvinov / @tomlinsj - getting this done today.
